- menu_name: "服務項目"

- name: "聯絡我們"
  url: "/contact/"
  class: "services-contact"
  title: "Contact"

- name: "網站地圖"
  url: "/sitemap.xml"
  class: "sitemap-link"
  title: "Sitemap for Google Webmastertools"
